# Generated by Django 6.0.3 on 2026-03-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dproject1', '0013_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
